<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- Sample XML document to test reading complex DOCTYPE element. -->

<!-- The XML document type declaration contains or points to markup
     declarations that provide a grammar for a class of documents. -->

<!DOCTYPE chapter [
    <!ELEMENT chapter (title,para+)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT para (#PCDATA)>
]>

<chapter><title>Chapter 1</title>
  <para>More unexpert, I boast not: them let those</para>
  <para>Contrive who need, or when they need, not now.</para>
  <para>For while they sit contriving, shall the rest,</para>
  <para>Millions that stand in Arms, and longing wait</para>
</chapter>
